### ISSUE TITLE
Integrate https://release-monitoring.org for the most up to date packages

### ISSUE THREAD

**Issue by romulasry** [openSUSE/open-build-service#10834]
**Is your feature request related to a problem? Please describe.**
I would like the most up to date packages but sadly opensuse tumbleweed doesn't have them

**Describe the solution you'd like**
Integration of https://release-monitoring.org to keep packages up to date

**Describe alternatives you've considered**
None.

**Additional context**
Someone suggested this and it seems like a good idea.

**Comment by hennevogel** [comment]
What do you imagine the OBS to do?

**Comment by Alexander-Wilms** [comment]
Flathub has support for automatically updating packages by referencing the [release-monitoring.org](https://release-monitoring.org) ID.

```yaml
      - type: archive
        url: https://github.com/vcmi/vcmi/archive/refs/tags/1.4.4.tar.gz
        sha256: 5231b37c1c54233c745052f4fc47efb4457cfb7f7316168ec1762f49b06a85e3
        x-checker-data:
          type: anitya
          project-id: 5456
          stable-only: true
          url-template: https://github.com/vcmi/vcmi/archive/refs/tags/$version.tar.gz
```
https://github.com/flathub/eu.vcmi.VCMI/blob/master/eu.vcmi.VCMI.yaml
https://release-monitoring.org/project/5456/

This results in PRs automatically being created, triggering a test build after which the PR gets automatically merged if the maintainer opts in.

It would be nice if OBS offered something similar with a bot opening requests to update the package. I don't know if it's necessary that the .changes file is maintained, but that could be automated as well by writing a script for each package that transforms the changelog contained in the source archive to the format required by OBS. Or it could still be done manually.

E.g.
```
Name:           vcmi
Version:        1.4.4
Release:        0
Summary:        An open-source project aiming to reimplement HMM3:WoG game engine
License:        GPL-2.0-only
Group:          Amusements/Games/Strategy/Turn Based
URL:            https://vcmi.eu/
Source:         https://github.com/vcmi/vcmi/archive/%{version}.tar.gz#/%{name}-%{version}.tar.gz
AnityaID:       5456
BuildRequires:  cmake >= 3.16.0
BuildRequires:  fdupes
```

To assemble the `Source` URL, the flatpak-external-data-checker (the bot that creates the PRs) supports sematic versioning fields `$major`, `$minor` and `$patch` in addition to $version: https://github.com/flathub-infra/flatpak-external-data-checker#url-templates

`"url-template": "https://www.example.com/$major.$minor/v$version.tar.gz"`
