### ISSUE TITLE
Markdown (multiline) wrongly rendered

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/open-build-service#11154]
Issue can be observed for example on
https://build.opensuse.org/request/show/893848

There is a comment, multiline markown, like

```
Package libcfile appears in cycle libcfile/libuna
Package libuna appears in cycle libcfile/libuna

x86_64:
  libuna-devel:
  - libuna:mini
  - libuna
  libuna1:
  - libuna:mini
  - libuna
```

Something like inline `CODE` blocks are still accepted and rendered correctly, only multi line )with three back ticks) are wrongly rendered
