### ISSUE TITLE
Branch Package Step Without Event Filter Creates A Package Link As Well

### ISSUE THREAD

**Issue by danidoni** [openSUSE/open-build-service#11869]
When you create a branch package step and don't filter any event, you get a branched package via the pull_request event and a linked package via the push event at the target project specified in the branch package step.

Expected Result
============
I expected the branch package to happen, but no package link anywhere.

How to Reproduce
===============
1. Set up the SCM/OBS Integration as descfribed in the [OBS User Guide]() ensuring you configure a branch package step and no event filtering.
2. Create a pull request in the source GitHub project.
3. Go to the target project in `b.o.o`.
4. You'll find a linked package having a name and the commit sha of the last PR's commit appended in the target project specified in the branch package step.

Extra info
=======
The workflows.yml file looks like this:
```
workflow:
  steps:
    - branch_package:
        source_project: home:danidoni
        source_package: hello_world
        target_project: home:danidoni
```
You can find it [here](https://github.com/danidoni/hello_world/blob/master/.obs/workflows.yml).
You can see a linked package like the one described above in [my OBS home project](https://build.opensuse.org/project/show/home:danidoni). Note that there is no branched package because it failed for some other reason not related to this issue, but the branched package would be in a subproject.
