### ISSUE TITLE
SCM/CI workflow does not report multibuild checks

### ISSUE THREAD

**Issue by perlpunk** [openSUSE/open-build-service#11975]
# Issue Description

I am trying to setup a workflow that tests os-autoinst for pull requests.
I am using `link_package` because with `branch_package` we cannot limit the platforms.

https://github.com/perlpunk/os-autoinst/blob/master/.obs/workflows.yml
```
pr:
  steps:
  - link_package:
      source_project: devel:openQA
      source_package: os-autoinst
      target_project: home:tinita:branches:devel:openQA:GitHubLink
  - configure_repositories:
      project: home:tinita:branches:devel:openQA:GitHubLink
      repositories:
      - name: openSUSE_Tumbleweed
        target_project: openSUSE:Factory
        target_repository: snapshot
        architectures: [ x86_64, aarch64 ]
      - name: openSUSE_Leap_15.3
        target_project: devel:openQA:Leap:15.3
        target_repository: openSUSE_Leap_15.3
        architectures: [ x86_64 ]
      - name: openSUSE_Leap_15.2
        target_project: devel:openQA:Leap:15.2
        target_repository: openSUSE_Leap_15.2
        architectures: [ x86_64 ]
```

Expected Result
============

The package is multibuild: https://build.opensuse.org/package/show/devel:openQA/os-autoinst
As I have configured 4 platforms, I would expect to see 8 checks reported back to github.
But I only see 4, which appear after the tests for the first of the multibuild (os-autoinst) have finished.
The 4 for os-autoinst-test are never appearing, although the builds are showing up here:
https://build.opensuse.org/package/show/home:tinita:branches:devel:openQA:GitHubLink:perlpunk:os-autoinst:PR-10/os-autoinst

https://github.com/perlpunk/os-autoinst/pull/10
```
OBS: os-autoinst - openSUSE_Leap_15.2/x86_64
Details
￼
OBS: os-autoinst - openSUSE_Leap_15.3/x86_64
Details
￼
OBS: os-autoinst - openSUSE_Tumbleweed/aarch64
Details
￼
OBS: os-autoinst - openSUSE_Tumbleweed/x86_64
Details
```
It's now almost 40 minutes after the builds have finished, so I assume there is something wrong.
