### ISSUE TITLE
SCM/CI workflows: Support for multiple path elements in configure_repositories

### ISSUE THREAD

**Issue by mwilck** [openSUSE/open-build-service#12103]
[The configure_repositories Step](https://openbuildservice.org/2021/08/02/link-package-configure-repositories-and-ui/) describes how to set up custom reposititories for a branched package in OBS.

For SLE targets, more often than not multiple repositories have to be defined, like this:
```
  <repository name="SLE_15_SP4">
    <path project="openSUSE:Backports:SLE-15-SP4" repository="standard"/>
    <path project="SUSE:SLE-15-SP4:GA" repository="pool"/>
    <arch>x86_64</arch>
  </repository>
```
Otherwise not all `BuildRequires` can be satisfied.

Is this possible with `configure_repositories`, and if yes, how?

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support multiple path elements for the configure_repositories step](https://trello.com/c/ECm0EQhU/2469-support-multiple-path-elements-for-the-configurerepositories-step)

**Comment by mwilck** [comment]
Thanks for working on this! I'm assuming a post explaining the workflow modifications will follow?

**Comment by dmarcoux** [comment]
Yes, the changes are documented in the user documentation. When this is deployed. I'll share the link with you here to let you know :slightly_smiling_face:

**Comment by dmarcoux** [comment]
This is now live, here's the [documentation explaining the `configure_repositories` step with the `paths`](https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.scm_ci_workflow_integration.html#sec.obs.obs_scm_ci_workflow_integration.obs_workflows.steps.configure_repositories_architectures_for_a_project).

**Comment by mwilck** [comment]
As this is a breaking change, I suppose it has not been deployed on OBS yet, and won't be until after a public announcement?

**Comment by mwilck** [comment]
> As this is a breaking change, I suppose it has not been deployed on OBS yet, and won't be until after a public announcement?

Ok, so this is already live on build.opensuse.org. I learned it the hard way, as I got YAML syntax errors for the `configure_repositories` step formatted without `paths`.
*This is not a complaint*, I'm happy about it.

I don't think it works quite correct yet though. See my test PR [here](https://github.com/openSUSE/multipath-tools/pull/14). The SLE15-SP4 test run failed because of wrong repository configuration. The [configured repositories](https://build.opensuse.org/projects/home:mwilck:multipath:openSUSE:multipath-tools:PR-14/meta) in the created OBS project do not match what I specified in [workflows.yml](https://github.com/openSUSE/multipath-tools/blob/test/.obs/workflows.yml):

Input (`.obs/workflows.yml`):
```
          - name: SLE_15_SP4
            paths:
              - target_project: openSUSE:Backports:SLE-15-SP4
                target_repository: standard
              - target_project: SUSE:SLE-15-SP4:GA
                target_repository: pool
            architectures:
              - x86_64
              - s390x
              - ppc64le
              - aarch64
```

Output (OBS project meta);

```
  <repository name="SLE_15_SP4">
    <path project="home:mwilck:multipath" repository="SLE_15_SP4"/>
    <arch>x86_64</arch>
    <arch>s390x</arch>
  </repository>
```
