### ISSUE TITLE
GitHub integration crashes OBS workflow

### ISSUE THREAD

**Issue by ashaduri** [openSUSE/open-build-service#12199]
# Issue Description
I followed the manual on using [OBS as a CI](https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.scm_ci_workflow_integration.html) and tried using on my gsmartcontrol repository:

GitHub repository: https://github.com/ashaduri/gsmartcontrol
OBS repository: https://build.opensuse.org/project/show/home:alex_sh:gsmartcontrol:github_ci:main

The GitHub webhook is set up to trigger on push and pull_request.
The response from OBS is `500 Internal Server Error`, with some HTML contents saying that OBS crashed.

This is my `.obs/workflows.yml` file contents:
```YAML
# This file describes OBS workflows:
# https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.scm_ci_workflow_integration.html

# Workflow for pull requests
#build_pull_request_workflow:
#  steps:
#    - branch_package:
#      source_project: home:alex_sh:gsmartcontrol:github_ci:main
#      source_package: gsmartcontrol
#      target_project: home:alex_sh:gsmartcontrol:github_ci:main
#
#    - configure_repositories:
#      project: home:alex_sh:gsmartcontrol:github_ci:main
#      repositories:
#
#        - name: openSUSE_Tumbleweed
#          paths:
#            - target_project: openSUSE:Factory
#              target_repository: snapshot
#          architectures:
#            - x86_64
#            - i586
#
#    - set_flags:
#      flags:
#        - type: publish
#          status: disable
#          project: home:alex_sh:gsmartcontrol:github_ci:main
#
#  filters:
#    event: pull_request
#    branches:
#      only:
#        - main


# Workflow for pushes
build_main_workflow:
  steps:
    - rebuild_package:
      project: home:alex_sh:gsmartcontrol:github_ci:main
      package: gsmartcontrol

    - configure_repositories:
      project: home:alex_sh:gsmartcontrol:github_ci:main
      repositories:

        - name: openSUSE_Tumbleweed
          paths:
            - target_project: openSUSE:Factory
              target_repository: snapshot
          architectures:
            - x86_64
            - i586

        - name: openSUSE_Leap_15.4
          paths:
            - target_project: openSUSE:Leap:15.4
              target_repository: standard
          architectures:
            - x86_64

        - name: openSUSE_Leap_15.3
          paths:
            - target_project: openSUSE:Leap:15.3
              target_repository: standard
          architectures:
            - x86_64

        - name: openSUSE_Factory_PowerPC
          paths:
            - target_project: openSUSE:Factory:PowerPC
              target_repository: standard
          architectures:
            - ppc64
            - ppc64le

        - name: openSUSE_Factory_ARM
          paths:
            - target_project: openSUSE:Factory:ARM
              target_repository: standard
          architectures:
            - aarch64
            - armv7l

        - name: SUSE_SLE-15-SP4
          paths:
            - target_project: SUSE:SLE-15-SP4:GA
              target_repository: standard
          architectures:
            - x86_64

        - name: SUSE_SLE-12-SP5
          paths:
            - target_project: SUSE:SLE-12-SP5:GA
              target_repository: standard
          architectures:
            - x86_64

        - name: xUbuntu_21.10
          paths:
            - target_project: openSUSE:Tools
              target_repository: xUbuntu_21.10
            - target_project: Ubuntu:21.10
              target_repository: universe
          architectures:
            - x86_64

        - name: xUbuntu_20.04
          paths:
            - target_project: openSUSE:Tools
              target_repository: xUbuntu_20.04
            - target_project: Ubuntu:20.04
              target_repository: universe
          architectures:
            - x86_64

        - name: Fedora_Rawhide
          paths:
            - target_project: openSUSE:Tools
              target_repository: Fedora_Rawhide
            - target_project: Fedora:Rawhide
              target_repository: standard
          architectures:
            - x86_64

        - name: Fedora_35
          paths:
            - target_project: openSUSE:Tools
              target_repository: Fedora_35
            - target_project: Fedora:35
              target_repository: standard
          architectures:
            - x86_64
            - aarch64
            - armv7l
            - ppc64le

        - name: Fedora_34
          paths:
            - target_project: openSUSE:Tools
              target_repository: Fedora_34
            - target_project: Fedora:34
              target_repository: standard
          architectures:
            - x86_64

        - name: Debian_Unstable
          paths:
            - target_project: openSUSE:Tools
              target_repository: Debian_Unstable
            - target_project: Debian:Next
              target_repository: standard
          architectures:
            - x86_64
            - i586

        - name: Debian_Testing
          paths:
            - target_project: openSUSE:Tools
              target_repository: Debian_Testing
            - target_project: Debian:Testing
              target_repository: update
          architectures:
            - x86_64
            - i586

        - name: Debian_11
          paths:
            - target_project: openSUSE:Tools
              target_repository: Debian_11
            - target_project: Debian:11
              target_repository: standard
          architectures:
            - x86_64
            - i586

        - name: Debian_10
          paths:
            - target_project: openSUSE:Tools
              target_repository: Debian_10
            - target_project: Debian:10
              target_repository: standard
          architectures:
            - x86_64
            - i586

        - name: CentOS_8_Stream
          paths:
            - target_project: openSUSE:Tools
              target_repository: CentOS_8_Stream
            - target_project: Fedora:EPEL:8
              target_repository: CentOS
            - target_project: CentOS:CentOS-8:Stream
              target_repository: standard
          architectures:
            - x86_64

        - name: CentOS_8
          paths:
            - target_project: openSUSE:Tools
              target_repository: CentOS_8
            - target_project: Fedora:EPEL:8
              target_repository: CentOS
            - target_project: CentOS:CentOS-8
              target_repository: standard
          architectures:
            - x86_64

    - set_flags:
      flags:
        - type: publish
          status: enable
          project: home:alex_sh:gsmartcontrol:github_ci:main
        - type: debuginfo
          status: enable
          project: home:alex_sh:gsmartcontrol:github_ci:main

  filters:
    event: push
    branches:
      only:
        - main
```

GitHub sent headers:
```
Request URL: https://build.opensuse.org/trigger/workflow?id=5904
Request method: POST
Accept: */*
content-type: application/json
User-Agent: GitHub-Hookshot/e76a539
X-GitHub-Delivery: 68db3d6a-8d89-11ec-9e7e-f85327a21ced
X-GitHub-Event: push
X-GitHub-Hook-ID: 343177367
X-GitHub-Hook-Installation-Target-ID: 341614595
X-GitHub-Hook-Installation-Target-Type: repository
X-Hub-Signature: sha1=a4553283b658582d5bafaaa29a37df05bbe2c90e
X-Hub-Signature-256: sha256=4014a2a42881f68fe4bc900e265ac5a3ecfba86e1ef4120be645c5d394b02527
```

Expected Result
============
No crash, successful builds.

Further Information
===============
* A link to an OBS instance showing the issue: https://build.opensuse.org/repositories/home:alex_sh:gsmartcontrol:github_ci:main

* Exact server version (in case a private instance is used): It's a public OBS instance.

Thanks!

**Comment by dmarcoux** [comment]
Hey @ashaduri,

the alignment of some YAML keys have to be corrected in the YAML you provided. While we should definitely better inform you about this, we simply crash right now... Sorry for that! We're going to improve this for sure. I'm tracking this now in our backlog.

The keys under each step are misaligned. I ran the YAML through a validator like http://www.yamllint.com/ and checked the result to see how each step looks like.

For example, this YAML:
```yaml
build_main_workflow:
  steps:
    - rebuild_package:
      project: home:alex_sh:gsmartcontrol:github_ci:main
      package: gsmartcontrol
```

should instead be like this:

```yaml
build_main_workflow:
  steps:
    - rebuild_package:
        project: home:alex_sh:gsmartcontrol:github_ci:main
        package: gsmartcontrol
```

Once this is addressed, it should work :slightly_smiling_face:. Let me know how it goes.

**Comment by dmarcoux** [comment]
[Exception](https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/620a3af984bf46054d0886e7) on Errbit.

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Validate .obs/workflows.yml with a schema validation](https://trello.com/c/HcN8VVkd/2285-validate-obs-workflowsyml-with-a-schema-validation)

**Comment by ashaduri** [comment]
Thanks!

I tried matching the yaml indents (I really hope a better syntax is used here). Using yamllint, the examples and my file seem to give similar output. However, now I get `HTTP 400`:
```XML
<status code="400" origin="backend">
  <summary>no repository defined</summary>
</status>
```
even though I have more than enough repositories defined in `workflows.yaml`.

I understand this is a different issue, so if needed, I can open another report.

The new `workflows.yaml`:
```YAML
# This file describes OBS workflows:
# https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.scm_ci_workflow_integration.html

# Workflow for pull requests
build_pull_request_workflow:
  steps:
    - branch_package:
        source_project: home:alex_sh:gsmartcontrol:github_ci:main
        source_package: gsmartcontrol
        target_project: home:alex_sh:gsmartcontrol:github_ci:main

    - configure_repositories:
        project: home:alex_sh:gsmartcontrol:github_ci:main
        repositories:
          - name: openSUSE_Tumbleweed
            paths:
              - target_project: openSUSE:Factory
                target_repository: snapshot
            architectures:
              - x86_64
              - i586

    - set_flags:
        flags:
          - type: publish
            status: disable
            project: home:alex_sh:gsmartcontrol:github_ci:main

  filters:
    event: pull_request
    branches:
      only:
        - main


# Workflow for pushes
build_main_workflow:
  steps:
    - rebuild_package:
        project: home:alex_sh:gsmartcontrol:github_ci:main
        package: gsmartcontrol

    - configure_repositories:
        project: home:alex_sh:gsmartcontrol:github_ci:main
        repositories:

          - name: openSUSE_Tumbleweed
            paths:
              - target_project: openSUSE:Factory
                target_repository: snapshot
            architectures:
              - x86_64
              - i586

          - name: openSUSE_Leap_15.4
            paths:
              - target_project: openSUSE:Leap:15.4
                target_repository: standard
            architectures:
              - x86_64

          - name: openSUSE_Leap_15.3
            paths:
              - target_project: openSUSE:Leap:15.3
                target_repository: standard
            architectures:
              - x86_64

          - name: openSUSE_Factory_PowerPC
            paths:
              - target_project: openSUSE:Factory:PowerPC
                target_repository: standard
            architectures:
              - ppc64
              - ppc64le

          - name: openSUSE_Factory_ARM
            paths:
              - target_project: openSUSE:Factory:ARM
                target_repository: standard
            architectures:
              - aarch64
              - armv7l

          - name: SUSE_SLE-15-SP4
            paths:
              - target_project: SUSE:SLE-15-SP4:GA
                target_repository: standard
            architectures:
              - x86_64

          - name: SUSE_SLE-12-SP5
            paths:
              - target_project: SUSE:SLE-12-SP5:GA
                target_repository: standard
            architectures:
              - x86_64

          - name: xUbuntu_21.10
            paths:
              - target_project: openSUSE:Tools
                target_repository: xUbuntu_21.10
              - target_project: Ubuntu:21.10
                target_repository: universe
            architectures:
              - x86_64

          - name: xUbuntu_20.04
            paths:
              - target_project: openSUSE:Tools
                target_repository: xUbuntu_20.04
              - target_project: Ubuntu:20.04
                target_repository: universe
            architectures:
              - x86_64

          - name: Fedora_Rawhide
            paths:
              - target_project: openSUSE:Tools
                target_repository: Fedora_Rawhide
              - target_project: Fedora:Rawhide
                target_repository: standard
            architectures:
              - x86_64

          - name: Fedora_35
            paths:
              - target_project: openSUSE:Tools
                target_repository: Fedora_35
              - target_project: Fedora:35
                target_repository: standard
            architectures:
              - x86_64
              - aarch64
              - armv7l
              - ppc64le

          - name: Fedora_34
            paths:
              - target_project: openSUSE:Tools
                target_repository: Fedora_34
              - target_project: Fedora:34
                target_repository: standard
            architectures:
              - x86_64

          - name: Debian_Unstable
            paths:
              - target_project: openSUSE:Tools
                target_repository: Debian_Unstable
              - target_project: Debian:Next
                target_repository: standard
            architectures:
              - x86_64
              - i586

          - name: Debian_Testing
            paths:
              - target_project: openSUSE:Tools
                target_repository: Debian_Testing
              - target_project: Debian:Testing
                target_repository: update
            architectures:
              - x86_64
              - i586

          - name: Debian_11
            paths:
              - target_project: openSUSE:Tools
                target_repository: Debian_11
              - target_project: Debian:11
                target_repository: standard
            architectures:
              - x86_64
              - i586

          - name: Debian_10
            paths:
              - target_project: openSUSE:Tools
                target_repository: Debian_10
              - target_project: Debian:10
                target_repository: standard
            architectures:
              - x86_64
              - i586

          - name: CentOS_8_Stream
            paths:
              - target_project: openSUSE:Tools
                target_repository: CentOS_8_Stream
              - target_project: Fedora:EPEL:8
                target_repository: CentOS
              - target_project: CentOS:CentOS-8:Stream
                target_repository: standard
            architectures:
              - x86_64

          - name: CentOS_8
            paths:
              - target_project: openSUSE:Tools
                target_repository: CentOS_8
              - target_project: Fedora:EPEL:8
                target_repository: CentOS
              - target_project: CentOS:CentOS-8
                target_repository: standard
            architectures:
              - x86_64

    - set_flags:
        flags:
          - type: publish
            status: enable
            project: home:alex_sh:gsmartcontrol:github_ci:main
          - type: debuginfo
            status: enable
            project: home:alex_sh:gsmartcontrol:github_ci:main

  filters:
    event: push
    branches:
      only:
        - main
```

Thanks!
