### ISSUE TITLE
SCM/CI integration, OBS can't download `.obs/workflows.yml` on `tag_push` from a github repository

### ISSUE THREAD

**Issue by davidcassany** [openSUSE/open-build-service#13206]
# Issue Description
I am trying to trigger services of a package when a tag is pushed to the related github repository. For some reason it always fails and it looks like OBS tries to use the tag sha against the github API and it doesn't seam to be supported.

In OBS workflow run reports I can see this error:

```
<status code="non_existent_workflows_file">
  <summary>.obs/workflows.yml could not be downloaded from the SCM branch/commit 0f399c267d91f7a0ff00cec961d9b3b9ab8f3c8f: GET https://api.github.com/repos/rancher/elemental-cli/contents//.obs/workflows.yml?ref=0f399c267d91f7a0ff00cec961d9b3b9ab8f3c8f: 404 - No commit found for the ref 0f399c267d91f7a0ff00cec961d9b3b9ab8f3c8f // See: https://docs.github.com/v3/repos/contents/</summary>
</status>
```

From a cloned repo I can see:
```
$ git show-ref --tags
....
0f399c267d91f7a0ff00cec961d9b3b9ab8f3c8f refs/tags/v0.1.0
```

So OBS uses the tag hash to download the workflow against github API, but this doesn't seam to work. [1] does not work, but [2] seams to work fine.

[1] https://api.github.com/repos/rancher/elemental-cli/contents//.obs/workflows.yml?ref=0f399c267d91f7a0ff00cec961d9b3b9ab8f3c8f

[2] https://api.github.com/repos/rancher/elemental-cli/contents//.obs/workflows.yml?ref=v0.1.0

Expected Result
============
The workflow run should not fail, it should be capable to find `.obs/workflows.yml` in a github repository from an tag_push` event.

How to Reproduce
===============
Set a workflow in some github repository as:
```yaml
tag_workflow:                                                                                                                                                                                                                                  
  steps:                                                                                                                                                                                                                                           
    - trigger_services:                                                                                                                                                                                                                            
        project: <my_prj>
        package: <my_pkg>
  filters:                                                                                                                                                                                                                                         
    event: tag_push
```

Set a webhook to make use of an OBS workflow token on `branch or tag creation` and `pushes` events.

Finally push a new tag to the repository and the triggered workflow will fail to fetch `.obs/workflow` from the repository.

Further Information
===============
* A link to an OBS instance showing the issue
* Exact server version (in case a private instance is used)

**Comment by dmarcoux** [comment]
Thank you @davidcassany for the report.

OBS looks for `.obs/workflows.yml` in the GitHub repository for the git ref of the tag (in this case `0f399c267d91f7a0ff00cec961d9b3b9ab8f3c8f`). Instead, OBS should use the commit which the tag points to. This would be `63c461339929adda664e0bd0b974a2d66a567125`, see:

```bash
# Inside the rancher/elemental-cli
$ git show v0.1.0
tag v0.1.0
Tagger: David Cassany <dcassany@suse.com>
Date:   Mon Oct 10 16:04:01 2022 +0200

Tag for version 0.1.0

commit 63c461339929adda664e0bd0b974a2d66a567125 (tag: v0.1.0)
(...)
```

**Comment by dmarcoux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix issue for GitHub's tag_push event](https://trello.com/c/2fdAo9zJ/196-fix-issue-for-githubs-tagpush-event)

**Comment by dmarcoux** [comment]
This issue might be coming from the changes in #12673.

**Comment by hennevogel** [comment]
@davidcassany this is deployed now, let us know how it goes please! Sorry for the inconvenience...

**Comment by davidcassany** [comment]
> @davidcassany this is deployed now, let us know how it goes please! Sorry for the inconvenience...

Thanks much! Probably it will take me a while to verify it since I need to tag to actually test it and probably this will happen on mid January.

**Comment by davidcassany** [comment]
@hennevogel I am sorry to report our first attempt to see the fix in action did not succeed... 😞  I can't really track what when wrong as I don't actually understand which was the actual call to github API by looking at the OBS traces on my tokens records.

This time I got this error:

```xml
<status code="non_existent_repository">
  <summary>"" is invalid as a repository identifier. Use the user/repo (String) format, or the repository ID (Integer), or a hash containing :repo and :user keys.</summary>
</status>
```

Worflow run records can be found [here](https://build.opensuse.org/my/tokens/6602/workflow_runs/102347). The payload in there looks sane, so it is a bit unclear to me which is the field missing, looks like GitHub API complaints about a missing repository identifier.

I triggered the workflow by pusing a new tag:

```bash
# on main branch
$ git tag v1.1.1
$ git push origin v1.1.1
```

With a workflow yaml as:

```yaml
tag_workflow:
  steps:
    ...
  filters:
    branches:
      only:
        - main
    event: tag_push
```

My github webhook is triggered on
* Branch or tag creation
* Pull requests
* Pushed

Looks like everything is properly set on my side 🤷🏽‍♂️
