### ISSUE TITLE
Step::RebuildPackage & Step::TriggerServices do not create EventSubscription

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#13535]
For both of those steps people assume status reports on the SCM but they don't create `EventSubscription`s if they are the only steps in the workflow.yml

**Comment by hennevogel** [comment]
Like 

```yml
push_workflow:
  steps:
    - rebuild_package:
        project: home:hennevogel:myfirstproject
        package: ctris
  filters:
    event: push
    branches:
      only:
        - master
```
