### ISSUE TITLE
Workflow sanity checks on tag_push events are not applied to the appropriate workflow

### ISSUE THREAD

**Issue by davidcassany** [openSUSE/open-build-service#14048]
# Issue Description
This seams to be related to #13841 and #13206. I have the feeling that #13841 is too restrictive and causes the push tag event to fail even when there is no branch filter defined on that specific workflow.

Here is a failed [workflow run](https://build.opensuse.org/my/tokens/6602/workflow_runs/130005) showing the error message:
```
Filters for branches are not supported for the tag push event, Documentation for filters: https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.scm_ci_workflow_integration.html#sec.obs.obs_scm_ci_workflow_integration.setup.obs_workflows.filters
```

However the workflow definition was:

```yaml
push_workflow:
  steps:
    - trigger_services:
        project: isv:Rancher:Elemental:Dev
        package: elemental-toolkit
  filters:
    branches:
      only:
        - main
    event: push

tag_workflow:
  steps:
    - trigger_services:
        project: isv:Rancher:Elemental:Staging
        package: elemental-toolkit
    - trigger_services:
        project: isv:Rancher:Elemental:Dev
        package: elemental-toolkit
  filters:
    event: tag_push

pr_workflow:
  steps:
    - branch_package:
        source_project: isv:Rancher:Elemental:Dev
        source_package: elemental-toolkit
        target_project: isv:Rancher:Elemental:PR
  filters:
    event: pull_request
    branches:
      only:
        - main
```

As you can see there is no branch filter for the even `tag_push`, however there is the branch filter on other workflows. Feels like #13841 did not consider the case of multiple workflows within the same file.  I am not versed on ruby and even less on rails, hence I am not fully following the code details.

Expected Result
============
The tag push event is properly executed and it triggers the source services based on a new tag.

How to Reproduce
===============
Include a workflows.yml file with multiple workflows, at least one filtering on branch and another one filtering only on tag_push event. Then if a tag is pushed to the repository the sanity check included within #13841 blocks the workflow attached to tag pushes and errors out.

Further Information
===============
* A link to an OBS instance showing the issue: https://build.opensuse.org/my/tokens/6602/workflow_runs/130005
