### ISSUE TITLE
Provide repository branch name as an additional placeholder variable

### ISSUE THREAD

**Issue by jfehlig** [openSUSE/open-build-service#14054]
**Is your feature request related to a problem? Please describe.**
SCMs that provide sources for obs packages may contain many branches. E.g. a branch for each downstream product using the sources. It would be nice to use a common scm webhook for push events to any branch in the scm. The templated workflow triggered by the webhook could be filled with the branch name provided in the webhook payload.

**Describe the solution you'd like**
An new placeholder variable such as %{SCM_REPOSITORY_BRANCH}. Here's an example of how it could be used in a workflow description:

push_workflow:
  steps:
    - trigger_services:
        project: Devel:Virt:%{SCM_REPOSITORY_BRANCH}
        package: libvirt
    - rebuild_package:
        project: Devel:Virt:%{SCM_REPOSITORY_BRANCH}
        package: libvirt
  filters:
    event: push
    branches:
      ignore:
        - factory

**Describe alternatives you've considered**
An alternative is creating scm webhooks for each branch, if that's possible at github/gitlab.

**Comment by darix** [comment]
it is possible to create that per branch

https://github.com/openSUSE/open-build-service/blob/master/.obs/workflows.yml#L19

**Comment by jfehlig** [comment]
Ah, do you mean something like:

```
sp4-rebuild:
  steps:
    - trigger_services:
        project: Devel:Virt:SLE-15-SP4
        package: libvirt
    - rebuild_package:
        project: Devel:Virt:SLE-15-SP4
        package: libvirt
  filters:
    event: push
    branches:
      only:
        - v8.0.0-sle15sp4

sp5-rebuild:
  steps:
    - trigger_services:
        project: Devel:Virt:SLE-15-SP5
        package: libvirt
    - rebuild_package:
        project: Devel:Virt:SLE-15-SP5
        package: libvirt
  filters:
    event: push
    branches:
      only:
        - v9.0.0-sle15sp5
```

**Comment by darix** [comment]
1. trigger service already triggers a rebuild so you can remove that chunk. 
2. but yes the general approach is what you want.

**Comment by jfehlig** [comment]
Nice, thanks a lot for the suggestion! Here's the improved example

```
sp4-rebuild:
  steps:
    - trigger_services:
        project: Devel:Virt:SLE-15-SP4
        package: libvirt
  filters:
    event: push
    branches:
      only:
        - v8.0.0-sle15sp4

sp5-rebuild:
  steps:
    - trigger_services:
        project: Devel:Virt:SLE-15-SP5
        package: libvirt
  filters:
    event: push
    branches:
      only:
        - v9.0.0-sle15sp5

```
I'm fine with this alternative. But providing the branch name does allow for configuration like my original example, which doesn't necessarily require editing with each new branch.

**Comment by darix** [comment]
well you trade some flexibility ( not having to maintain a per branch block ) for another flexibility ( branch names and project names do not have to match )

**Comment by jfehlig** [comment]
Nod, and the second flexibility you mention is nice. Feel free to close the issue if adding branch name in the placeholder variables is undesirable.

**Comment by nickbroon** [comment]
Yes, I think having the branch name available as a variable would be useful. Having project named for a branch is a relative common pattern, and not having to repeat blocks for each new branch would be efficient.

Consider something like (where basics regex are supported in branch filters):

```
release_rebuilds:
  steps:
    - trigger_services:
        project: foo:release_branch:${SCM_REPOSITORY_BRANCH}
        package: foobar
  filters:
    event: push
    branches:
      only:
        - ^release/
```

**Comment by nickbroon** [comment]
Another useful variable would a variable with scm repository default branch name.
This would be useful when a common workflow is being used for multiple repo (ie `workflow_configuration_url`), so that default branch can be used in the `filters: branches:` as the default branch might not have the same name (main, master, etc) cross all repos using the common workflow_configuration_url. Something like:
```
workflow:
  steps:
    - rebuild_package:
        project: %{SCM_ORGANIZATION_NAME}
        package: %{SCM_REPOSITORY_NAME}
  filters:
    branches:
      only:
        - %{SCM_DEFAULT_BRANCH}

```
