### ISSUE TITLE
OBS SCM Workflow `branch_package` does not handle repositories correctly

### ISSUE THREAD

**Issue by LebedevRI** [openSUSE/open-build-service#14623]
When branching a package, it seems, the branched package inherits
the Repositories that were configured for the source **project** 
where the source package was located. It does not consider
the Repositories that were configured for the source **package** itself,
nor does the new (branched-to) package inherit the repositories
from it's new parent project.

**Comment by LebedevRI** [comment]
By per-package Repositories i mean the overrides to the Repository flags,
i.e. disabling/enabling build/publish/Debuginfo/Use for Build  flags
from the matrix that was inherited from the Project itself.

**Comment by hennevogel** [comment]
Can you maybe post an example of your workflow YAML and what you would expect to happen?

**Comment by LebedevRI** [comment]
Workflow:
```
develop:
  steps:
    - trigger_services:
        project: graphics:darktable:master
        package: rawspeed
  filters:
    event: push
    branches:
      only:
        - develop
pr:
  steps:
    - branch_package:
        source_project: graphics:darktable:master
        source_package: rawspeed
        target_project: graphics:darktable:github
  filters:
    event: pull_request
```
I.e. it branches https://build.opensuse.org/package/show/graphics:darktable:master/rawspeed

These are the Repositories configured for the **project** [graphics:darktable:master](https://build.opensuse.org/project/show/graphics:darktable:master): https://build.opensuse.org/projects/graphics:darktable:master/meta (TLDR: a lot of distros/repositories)
And here's overrides to those settings in the **package** [graphics:darktable:master/rawspeed](https://build.opensuse.org/package/show/graphics:darktable:master/rawspeed): https://build.opensuse.org/package/meta/graphics:darktable:master/rawspeed (TLDR: **only** `Tumbleweed`)

As you can see on [graphics:darktable:master/rawspeed](https://build.opensuse.org/package/show/graphics:darktable:master/rawspeed), there are only 6 builds,
but in a branched package, all of the builds configured for the source **package** are performed:
https://build.opensuse.org/project/show/graphics:darktable:github:darktable-org:rawspeed:PR-503

IOW, the source project Meta and source repository Meta aren't being merged,
only the formed is taken.
I would expect that branching would
