### ISSUE TITLE
Setting publish flag in OBS workflows seams to be ineffective

### ISSUE THREAD

**Issue by davidcassany** [openSUSE/open-build-service#14978]
# Issue Description
The issue raises when trying to create branches using SCM workflows based in github pull requests. We configured our workflow to actually publish the branched project and the flag appears if I check it in the UI, the problem is that builds are not actually published. As soon as I resave the meta (via UI or via `osc meta prj -e`) publishing start even if this flag was unchanged.

An example of a non published branched project can be seen [here](https://build.opensuse.org/project/show/isv:Rancher:Elemental:PR:rancher:elemental-operator:PR-474). The meta at project level clearly shows:

```xml
<publish>
  <enable/>
</publish>
```

The worflow that created such project is set as:

```yaml
pr_workflow:
  steps:
    - branch_package:
        source_project: isv:Rancher:Elemental:Dev
        source_package: elemental-operator
        target_project: isv:Rancher:Elemental:PR
    - set_flags:
        flags:
          - type: publish
            status: enable
            project: isv:Rancher:Elemental:PR
  filters:
    event: pull_request
    branches:
      only:
        - main
```

Expected Result
============
I would have expected the publishing falg to be applied from the first build and get binaries published so we can run some continuous integration processes based on OBS builds.

How to Reproduce
===============
Set a `branch_package` on github pull requests and set the publish flag to `enable` (see the setup above), then create a PR and the branch and build will happen as expected, however the publishing won't.

Further Information
===============
Nothing relevant

**Comment by hennevogel** [comment]
This should be a simple `main_object.store` if `main_object` is a `Project`.

**Comment by hennevogel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix issue](https://trello.com/c/VhCyYJly/301-fix-issue)

**Comment by rubhanazeem** [comment]
@davidcassany it should be fixed now. Please let us know if it is still happening

**Comment by davidcassany** [comment]
@rubhanazeem sorry to come back to this topic late, until now I did not have a chance to exercise this issue again. I confirm I still face the issue. It is not fixed...

I created a fake [PR for testing purposes](https://github.com/rancher/elemental-operator/pull/573) in case you want to check it and have a look. I'd be happy to also demo it if needed or you struggle to reproduce it. I think I am not missing anything. Our current workflow setup has not changed, it still is

```yaml
pr_workflow:
  steps:
    - branch_package:
        source_project: isv:Rancher:Elemental:Dev
        source_package: elemental-operator
        target_project: isv:Rancher:Elemental:PR
    - branch_package:
        source_project: isv:Rancher:Elemental:Dev
        source_package: elemental-operator-helm
        target_project: isv:Rancher:Elemental:PR
    - branch_package:
        source_project: isv:Rancher:Elemental:Dev
        source_package: elemental-operator-crds-helm
        target_project: isv:Rancher:Elemental:PR
    - branch_package:
        source_project: isv:Rancher:Elemental:Dev
        source_package: operator-image
        target_project: isv:Rancher:Elemental:PR
    - branch_package:
        source_project: isv:Rancher:Elemental:Dev
        source_package: seedimage-builder
        target_project: isv:Rancher:Elemental:PR
    - set_flags:
        flags:
          - type: publish
            status: enable
            project: isv:Rancher:Elemental:PR
 ```
 
 And I can see the flag in meta as: 
 
 ```xml
 <publish>
  <enable/>
</publish>
```

You can see the [generated project](https://build.opensuse.org/project/show/isv:Rancher:Elemental:PR:rancher:elemental-operator:PR-573) did not publish anything after the build. The interesting thing is that the meta XML looks correct and if I save it again (even without any change) publishing automatically starts in a matter of few seconds 🤷🏽‍♂️
