### ISSUE TITLE
[contrib] `rake docker:build` fails with Errno::EACCES: Permission denied @ rb_sysopen - /obs/src/api/log/bullet.log

### ISSUE THREAD

**Issue by valdrinkuchi** [openSUSE/open-build-service#15659]
Issue/Feature Description
====================
While following the instructions specified [here](https://github.com/openSUSE/open-build-service/blob/master/CONTRIBUTING.md), to setup local OBS development  I face the following error when running `rake docker:build`:
```sh
Errno::EACCES: Permission denied @ rb_sysopen - /obs/src/api/log/bullet.log
/obs/src/api/config/environments/development.rb:99:in `block (2 levels) in <top (required)>'
/obs/src/api/config/environment.rb:31:in `<top (required)>'
/usr/bin/bundle:25:in `load'
/usr/bin/bundle:25:in `<main>'
Tasks: TOP => dev:bootstrap => environment
(See full trace by running task with --trace)
docker compose stop
```

Expected Result
============
No permission issues should  be present and the development environment should work properly.

How to Reproduce
===============
1. Machine running on: `Ubuntu 22.04.3 LTS`
2. `Docker version 24.0.6, build ed223bc`
3. Follow instructions specified [here](https://github.com/openSUSE/open-build-service/blob/master/CONTRIBUTING.md)

**Comment by valdrinkuchi** [comment]
> Do you have a `docker-compose.override.yml` file in the top level of your checkout? What's the content?

```yml
# This file is generated by our Rakefile. Do not change it!
version: '2.1'
services:
  frontend:
    build:
      args:
        CONTAINER_USERID: 1000

    volumes:
      - ./docker-files/home/.bash_history:/home/frontend/.bash_history:Z
      - ./docker-files/home/.irb_history:/home/frontend/.irb_history:Z
      - ./docker-files/home/.pry_history:/home/frontend/.pry_history:Z
      - ./docker-files/home/.irbrc:/home/frontend/.irbrc:Z
      - ./docker-files/home/.pryrc:/home/frontend/.pryrc:Z

```

**Comment by valdrinkuchi** [comment]
I deleted the repository and cloned it one more time just to make sure that I follow the instructions correctly.
Although it still fails, this time I receive a lightly different error:

```sh
docker compose run --no-deps --rm frontend bundle exec rake dev:bootstrap RAILS_ENV=development
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
Setting up the database configuration...
Creating config/config/database.yml from config/config/database.yml.example
rake aborted!
Errno::EACCES: Permission denied @ rb_sysopen - config/database.yml
/obs/src/api/lib/tasks/dev/rake_support.rb:22:in `copy_example_file'
/obs/src/api/lib/tasks/dev.rake:10:in `block (2 levels) in <top (required)>'
/usr/bin/bundle:25:in `load'
/usr/bin/bundle:25:in `<main>'
Tasks: TOP => dev:bootstrap => dev:prepare
(See full trace by running task with --trace)
docker compose stop
[+] Running 1/1
 ⠿ Container open-build-service-db-1  Stopped                              0.4s
rake aborted!
Command failed with status (1): [docker compose run --no-deps --rm frontend...]
/home/valdrin/Desktop/open-build-service/Rakefile:39:in `block (2 levels) in <top (required)>'
Tasks: TOP => docker:build
(See full trace by running task with --trace)
```

```yml
# This file is generated by our Rakefile. Do not change it!
version: '2.1'
services:
  frontend:
    build:
      args:
        CONTAINER_USERID: 1000

    volumes:
      - ./docker-files/home/.bash_history:/home/frontend/.bash_history:Z
      - ./docker-files/home/.irb_history:/home/frontend/.irb_history:Z
      - ./docker-files/home/.pry_history:/home/frontend/.pry_history:Z
      - ./docker-files/home/.irbrc:/home/frontend/.irbrc:Z
      - ./docker-files/home/.pryrc:/home/frontend/.pryrc:Z

```
