### ISSUE TITLE
devel:BCI:16.0/kiwi-image is not being updated by a push to SCM

### ISSUE THREAD

**Issue by dcermak** [openSUSE/open-build-service#17425]
# Issue Description

We have setup a webhook for OBS' SCM integration for the BCI-dockerfile-generator repository. We have a separate `.obs/workflows.yml` file for each branch. For the `16.0` branch, we trigger the services on OBS in `devel:BCI:16.0`, which would instruct OBS to run the equivalent of `osc service remoterun` (see https://github.com/SUSE/BCI-dockerfile-generator/blob/16.0/.obs/workflows.yml):

```yaml
# snip
refresh_devel_BCI:
  steps:
# snip
    - trigger_services:
        project: devel:BCI:16.0
        package: kiwi-image
```

However, this stopped working recently (maybe for the last month? That branch sees very few commits). E.g. this change: https://github.com/SUSE/BCI-dockerfile-generator/commit/4995d8ffb8e67503d5914a2fc0fe09616118533b should have triggered a source update on https://build.opensuse.org/package/show/devel:BCI:16.0/kiwi-image, but it is not visible there. The corresponding workflow run succeeded, but no remote source service run happened: https://build.opensuse.org/my/tokens/8667/workflow_runs/437276

Also, there's no service failure. So no idea what went wrong

Expected Result
============
The package `kiwi-image` should have been updated.
