### ISSUE TITLE
Kiwi::Repository validations for source_path not valid flickers

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/open-build-service#3247]
https://travis-ci.org/openSUSE/open-build-service/jobs/242713879

```
Failures:

  1) Kiwi::Repository validations for source_path not valid

     Failure/Error: is_expected.not_to allow_value(string).for(:source_path)

     

       failure: 1 tests, on:

       http://TX5RK@P

     

       After setting :source_path to ‹"http://TX5RK@P"›, the matcher expected

       the Kiwi::Repository to be invalid, but it was valid instead.

     # ./spec/models/kiwi/repository_spec.rb:58:in `block (6 levels) in <top (required)>'

     # ./spec/models/kiwi/repository_spec.rb:57:in `block (5 levels) in <top (required)>'

     # ./spec/support/logging.rb:4:in `block (2 levels) in <top (required)>'

     # ------------------

     # --- Caused by: ---

     #   After setting :source_path to ‹"http://TX5RK@P"›, the matcher expected

     #   the Kiwi::Repository to be invalid, but it was valid instead.

     #   ./spec/models/kiwi/repository_spec.rb:58:in `block (6 levels) in <top (required)>'


```

https://travis-ci.org/openSUSE/open-build-service/jobs/242713585

```
Kiwi::Repository validations for source_path not valid

     Failure/Error: is_expected.not_to allow_value(string).for(:source_path)

     

       failure: 0 tests, on:

       https://@G

     

       After setting :source_path to ‹"https://@G"›, the matcher expected the

       Kiwi::Repository to be invalid, but it was valid instead.

     # ./spec/models/kiwi/repository_spec.rb:58:in `block (6 levels) in <top (required)>'

     # ./spec/models/kiwi/repository_spec.rb:57:in `block (5 levels) in <top (required)>'

     # ./spec/support/logging.rb:4:in `block (2 levels) in <top (required)>'

     # ------------------

     # --- Caused by: ---

     #   After setting :source_path to ‹"https://@G"›, the matcher expected the

     #   Kiwi::Repository to be invalid, but it was valid instead.

     #   ./spec/models/kiwi/repository_spec.rb:58:in `block (6 levels) in <top (required)>'
```
