### ISSUE TITLE
Add line between every binary

### ISSUE THREAD

**Issue by Ana06** [openSUSE/open-build-service#4525]
@coolo complained about the binary download page, as it is not easy to know what download button is for every binary. For example, check: https://build.opensuse.org/package/binaries/devel:openQA/openQA?repository=openSUSE_Leap_42.3

![image](https://user-images.githubusercontent.com/16052290/36383683-2d89a2a6-158d-11e8-846a-5bce4c5d64d1.png)

We want to add a line between every binary to separate them. :bowtie:

**Comment by hennevogel** [comment]
I rather would like to have something like

```css
li { background: green; }
li:nth-child(odd) { background: red; }
```
