### ISSUE TITLE
[beta] new UI can be too narrow

### ISSUE THREAD

**Issue by aspiers** [openSUSE/open-build-service#6033]
# Issue Description

Just like with GitHub, enforcing a maximum width on the main content of each page in the layout can cause things to be too squashed and waste a lot of valuable screen space.

How to Reproduce
===============
1. Join the beta program
2. Go to https://build.opensuse.org/package/show/systemsmanagement:sumaform:opensuse423/cloud-init
3. See something like this:

![obs-width](https://user-images.githubusercontent.com/100738/46533397-51f0f780-c89c-11e8-82b3-c01e125e74e5.png)

4. Notice how certain lines are needlessly wrapped, and how much wasted space there is.

Expected Result
===============

Tweaking the width gives a much nicer result:

![obs-width2](https://user-images.githubusercontent.com/100738/46534036-b745e800-c89e-11e8-9c9c-f188589a494e.png)

However, everyone's tastes / browsers / displays are different, so this should be adjustable.

**Comment by dmarcoux** [comment]
Thank you @aspiers for the feedback. We definitely need to use the space when available.

I'm not sure though about the adjustable width. However, let's say that we want to move forward with this proposal. How would you want to set this?  In [the user profile](https://build.opensuse.org/user/show/dmarcoux)?

**Comment by aspiers** [comment]
Ideally it would be settable by dragging the (perhaps invisible) border with the mouse, just like resizing normally happens.  Divorcing the setting from the view which it affects will reduce usability IMHO.  The way Chrome's inspector handles boundaries is a good example to follow.

**Comment by aspiers** [comment]
Also, I guess the setting should be stored in a cookie, so that it is per browser/machine.  It wouldn't make sense to have the same setting for a user's laptop and workstation, so per-account doesn't make sense.

**Comment by hellcp** [comment]
I would say that adding one more breakpoint to preset set by bootstrap would be enough (not to break breakpoints set for smaller devices). Currently, default bootstrap breakpoints that are used in OBS are 
```css
.container {
 width:100%;
 padding-right:15px;
 padding-left:15px;
 margin-right:auto;
 margin-left:auto
}
@media (min-width: 576px) {
 .container {
  max-width:540px
 }
}
@media (min-width: 768px) {
 .container {
  max-width:720px
 }
}
@media (min-width: 992px) {
 .container {
  max-width:960px
 }
}
@media (min-width: 1200px) {
 .container {
  max-width:1140px
 }
}
```
adding
```css
@media (min-width: 1600px) {
 .container {
  max-width:1540px
 }
}
```
would solve the issue for at least 1080p displays at 100% viewpoint width.
