### ISSUE TITLE
Excessive Padding

### ISSUE THREAD

**Issue by dmarcoux** [openSUSE/open-build-service#6587]
# Issue Description
In comparison with the old UI, we seem to be a bit excessive with the padding. To see what I mean, just compare https://build.opensuse.org/project/show/home:dmarcoux in the old and new UI. In the old UI, we can display ~20 packages while we display only 10 packages in the same area in the new UI.

Expected Result
============
I expect information to be efficiently presented to the user, without excessive padding.

How to Reproduce
===============
1. Go to https://build.opensuse.org/project/show/home:dmarcoux while not being in the beta.
2. See the number of packages displayed (~20 packages)
3. Join the beta and go again to https://build.opensuse.org/project/show/home:dmarcoux
4. See the number of packages displayed (only 10 packages)

Further Information
===============
This was reported in the opensuse-buildservice@opensuse.org following [our announcement](https://openbuildservice.org/2018/12/10/revamping-project-ui/), but also before in other GitHub issues like #6299 and #6049. We did address those issues, but we still need to address this in other areas of the new UI.

Comparison of what is visible on my screen when I'm on https://build.opensuse.org/project/show/home:dmarcoux (so without having to scroll)

The old UI:
![old-ui](https://user-images.githubusercontent.com/1102934/49866669-aa96c080-fe08-11e8-846d-8bbc7687c631.png)

The new UI:
![new-ui](https://user-images.githubusercontent.com/1102934/49866679-af5b7480-fe08-11e8-95c3-13fe542255d6.png)

**Comment by Qantas94Heavy** [comment]
Agree. The new UI also appears to fill up the whole screen, making it hard to read as it leaves very little room for white space. Personally, I have to resize the window to 80% to make it more usable.

**Comment by dmarcoux** [comment]
As for the new UI filling up the whole screen, this is intentional. It was added after the discussions in the issue #6033.

We are also thinking about making this adjustable. However, it's not possible right now.

**Comment by vpereira** [comment]
I disagree, for me the padding and white space in general reduces the cognitive load. IMO is much more pleasant to read the package names in the new one than in the older one.

**Comment by Vogtinator** [comment]
I'm using a set of CSS overrides to get more content onto a single monitor area:

```
body {
    font-size: 90% !important;
    line-height: 1.1 !important;
}

.mb-3, .my-3, .mt-3 {
    margin-bottom: 0.5rem !important;
    margin-top: 0.5rem !important;
}

#log-space-wrapper pre {
    font-size: 90% !important;
}
```

Before:

![image](https://user-images.githubusercontent.com/1622084/62824597-bc4f8400-bba0-11e9-9673-8d299f0fce75.png)

After:

![image](https://user-images.githubusercontent.com/1622084/62824598-c6718280-bba0-11e9-8531-079a87f993ce.png)

**Comment by stbuehler** [comment]
I'm using 80% browser zoom with this in stylish (still too much padding in the comment part):

```css
body {
    line-height: 1.15;
}
.m-2 {
    margin: 0 !important;
    margin-bottom: 0.25rem !important;
}
.mb-3, .my-3 {
    margin-bottom: 0.25rem !important;
}
.table-sm th, .table-sm td {
    padding-top: 0;
    padding-bottom: 0;
}
.card-body {
    padding-top: 0.25rem;
    padding-bottom: 0.25rem;
}
.nav-link {
    padding-top: 0.25rem;
    padding-bottom: 0.25rem;
}
#personal-navigation .nav-link {
    padding-top: 0.25rem;
    padding-bottom: 0.25rem;
}
.pt-2, .py-2 {
    padding-top: 0.25rem !important;
}
ol.breadcrumb {
    padding-top: 0.25rem;
}
.breadcrumb {
    padding-top: 0.25rem;
    padding-bottom: 0.25rem;
    margin-bottom: 0;
}
```

![2019-08-13-125105_1916x1040_scrot](https://user-images.githubusercontent.com/528446/62936310-c2747900-bdc9-11e9-8446-417aa5d9da50.png)
